# name: CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-publish:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm ci

#       - name: Build library
#         run: npm run build

#       - name: Set up Git
#         run: |
#           git config --global thieuluan
#           git config --global thieuluan.dev@gmail.com

#       - name: Commit and push version update
#         run: |
#           npm version patch -m "Bump version to %s [skip ci]"
#           git push --follow-tags

#       - name: Publish to NPM
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
#         run: |
#           echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
#           npm publish
